version: '3.8'

services:
  # Banco de dados
  db:
    build: ./db
    image: v1mr/postgres:1.0.0
    container_name: database
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  # API para acesso aos dados
  api:
    build: ./api
    image: v1mr/fastapi:1.0.0
    container_name: api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - "8000:8000"
    restart: always

  # Dashboard para visualização
  dashboard:
    build: ./dashboard
    image: v1mr/streamlit:1.0.0
    container_name: analytics
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
    ports:
      - "8501:8501"
    restart: always

volumes:
  postgres_data: